// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4nyE8LSafe_XPMSQuIa33dqTz5tVYCvU',
    appId: '1:374590747022:web:85b15e832d2173236734df',
    messagingSenderId: '374590747022',
    projectId: 'chat-app-6c77b',
    authDomain: 'chat-app-6c77b.firebaseapp.com',
    storageBucket: 'chat-app-6c77b.appspot.com',
    measurementId: 'G-B6SZ8HKR4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVi6inUtWHGoDtsu8H-7hUgOzy2zDIvkU',
    appId: '1:374590747022:android:1e360d7635b0173a6734df',
    messagingSenderId: '374590747022',
    projectId: 'chat-app-6c77b',
    storageBucket: 'chat-app-6c77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nB1mq81dhcbPoLoDAR18MWCoyH2soAI',
    appId: '1:374590747022:ios:143b6846c994b7186734df',
    messagingSenderId: '374590747022',
    projectId: 'chat-app-6c77b',
    storageBucket: 'chat-app-6c77b.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nB1mq81dhcbPoLoDAR18MWCoyH2soAI',
    appId: '1:374590747022:ios:143b6846c994b7186734df',
    messagingSenderId: '374590747022',
    projectId: 'chat-app-6c77b',
    storageBucket: 'chat-app-6c77b.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4nyE8LSafe_XPMSQuIa33dqTz5tVYCvU',
    appId: '1:374590747022:web:3ab43e732d6e1b566734df',
    messagingSenderId: '374590747022',
    projectId: 'chat-app-6c77b',
    authDomain: 'chat-app-6c77b.firebaseapp.com',
    storageBucket: 'chat-app-6c77b.appspot.com',
    measurementId: 'G-RMNMT9HE1V',
  );
}
